name: Static generation

on:
  push:
    branches: 'master'

jobs:
  build_site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js and pnpm
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c
        with:
          runtime: node@${{ matrix.node-version }}
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: build
        env:
          BASE_PATH: ''
        run: |
          pnpm build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
